const companies = [
  "Acko",
  "Adobe",
  "Airbase",
  "Airbnb",
  "Airbus",
  "Airtel X Labs",
  "Ajio",
  "Akamai",
  "AlphaGrep",
  "Alphonso",
  "Amagi",
  "Amazon",
  "American Express",
  "Angel One",
  "Ansys",
  "Anthem",
  "Apna",
  "AppDynamics",
  "Arcesium",
  "Arista",
  "Atlassian",
  "AutoDesk",
  "Auzmor",
  "Avail Finance",
  "Avalara",
  "BCG",
  "BNY Mellon",
  "Bain & Company",
  "Bankbazaar",
  "Belzabar",
  "Bharatpe",
  "Bigbasket",
  "Biofourmis",
  "Bizongo",
  "Blackbuck",
  "Blinkit",
  "BloomReach",
  "Booking",
  "Bright Money",
  "Broadcom",
  "Browserstack",
  "Bukuwarung",
  "Buyhatke",
  "Byjus",
  "C2FO",
  "Cadence",
  "CashFree",
  "Chargebee",
  "Chegg",
  "Chronus Software",
  "Cisco",
  "Citi Bank",
  "Citrix",
  "Citymall",
  "Clarisights",
  "ClearQuote",
  "ClearTax",
  "Clear Trip",
  "Cloootrack",
  "Cloud Lending",
  "Clumio",
  "Credgenics",
  "Codenation",
  "Cogoport",
  "Cohesity",
  "Coinbase",
  "Coinswitch",
  "CommercelQ",
  "Commvault",
  "Confluent",
  "CouchBase",
  "Cred",
  "Credit Suisse",
  "Crowdfire",
  "Cult Fit",
  "DE Shaw",
  "Daily Rounds",
  "Datadog",
  "Dealshare",
  "Delivery",
  "Dialpad",
  "Directi",
  "Dp world",
  "Dream 11",
  "Dremio",
  "Druva",
  "Duetshe bank",
  "Dunzo",
  "Eightfold ai",
  "Electronics Arts",
  "Eltropy",
  "Endurance",
  "Enfusion",
  "Epifi",
  "Expedia",
  "Falabella",
  "Fanclash",
  "Far Eye",
  "FarEye",
  "Fedility Investments",
  "Fleetx",
  "Flipkart",
  "Flock",
  "Today",
  "Fraazo",
  "FreeCharge",
  "FreshMenu",
  "FreshWorks",
  "FrontRow",
  "FunPlus",
  "GE Health Care",
  "Games 24x7",
  "GamesKraft",
  "Gartner",
  "Glance",
  "Gojek",
  "Goldman sachs",
  "GoodWorker",
  "Google",
  "Grab",
  "Graviton",
  "Groupon",
  "Groww",
  "Gupshup",
  "Harness",
  "Headout",
  "Hedge Fund",
  "Hotstar",
  "Idrive",
  "Indeed",
  "IndiaMart",
  "Indiagold",
  "Indmoney",
  "InsideView",
  "Intel",
  "Intuit",
  "Ion Trading",
  "Itilite",
  "Ixigo",
  "Jio",
  "JPMC",
  "Jumio",
  "Jungle Games",
  "Juniper Networks",
  "Jupiter Money",
  "Juspay",
  "KLA",
  "Khatabook",
  "Komprise",
  "Kuvera",
  "LambdaTest",
  "Leap Finance",
  "Leena ai",
  "Lenskart",
  "Licious",
  "Limeroad",
  "Linkedin",
  "Ling",
  "Livspace",
  "Loco",
  "MPL",
  "Magnitude",
  "MakeMyTrip",
  "Mastercard",
  "MathWorks",
  "McKinsey",
  "Medianet",
  "Meesho",
  "Meidatek",
  "Mentor Graphics",
  "Mfine",
  "Microsoft",
  "MindTickle",
  "MoenGage",
  "Money Control",
  "Moneyview",
  "MoonFrog",
  "Morgan Stanley",
  "MotorQ",
  "MSC",
  "MyKaarma",
  "Myntra",
  "NK Securities",
  "Nas Academy",
  "National Instruments",
  "Navi",
  "Nektar ai",
  "NetApp",
  "Netomi",
  "NewFold Digital",
  "Nference",
  "Nike",
  "Ninjacart",
  "NoBroker",
  "Noccarc",
  "Nurture Farm",
  "Nutanix",
  "Nvidia",
  "OCI",
  "OLX Group",
  "OkCredit",
  "Ola",
  "Oppo",
  "Oracle",
  "Oyo",
  "Palo Alto",
  "PayU",
  "Paypal",
  "Paytm",
  "Peak Ai",
  "PharmEasy",
  "Philips",
  "Phonepe",
  "Pickrr",
  "Plivo",
  "PlumHQ",
  "Porter",
  "Postman",
  "Practo",
  "Progress",
  "Property Guru",
  "Prophecy io",
  "Public Sapient",
  "Quad Eye",
  "Qualcomm",
  "Quizizz",
  "Rain Instant Pay",
  "Razorpay",
  "Rebel Foods",
  "Reliance Retail",
  "Revolut",
  "Rippling",
  "Rivigo",
  "Rubrik",
  "Rupeek",
  "SABRE",
  "SAP Labs",
  "Salesforce",
  "Salesken",
  "Samsung",
  "Sapient",
  "Schlumberger",
  "SenseHq",
  "Servicenow",
  "ShareChat",
  "Shiprocket",
  "Sigmoid",
  "Sigtuple",
  "Simpl",
  "Sixt",
  "Slack",
  "Smart Coin Financials",
  "Snowflake",
  "SocGen",
  "Sostronk",
  "Spinny",
  "SplashLearn",
  "Sprinklr",
  "Stashfin",
  "Stripe",
  "Sumo Logic",
  "Sumologic",
  "Swiggy",
  "Synopsys",
  "Target",
  "Tata 1mg",
  "Telstra",
  "Tesco",
  "Tesla",
  "Texas Instruments",
  "Times Internet",
  "Tokopedia",
  "TomTom",
  "Toppr",
  "Tower Research Capital",
  "Traveloka",
  "Trifacta",
  "Trink",
  "TruEra",
  "Turvo",
  "Twillio",
  "Twitter",
  "UOLO",
  "Uber",
  "Udaan",
  "UiPath",
  "Unacademy",
  "Upstox",
  "Urban Company",
  "Urban Ladder",
  "Visa",
  "Vmware",
  "Vogo",
  "Vymo",
  "Walmart",
  "Wells Fargo",
  "Western Digital",
  "Whatfix",
  "Wingify",
  "Winzo",
  "Wooger",
  "World Quant",
  "Xerox Research",
  "Xilinx",
  "Yellow AI",
  "Yubi",
  "Zendrive",
  "Zenefits",
  "Zerodha",
  "Zomato",
];
const companyCareerLinks = new Map([
  ["Acko", "https://www.acko.com/careers/"],
  ["Adobe", "https://www.adobe.com/careers.html"],
  ["Airbase", "https://www.airbase.com/careers"],
  ["Airbnb", "https://careers.airbnb.com/"],
  ["Airbus", "https://company.airbus.com/careers.html"],
  ["Airtel X Labs", "https://www.airtel.in/careers"],
  ["Ajio", "https://careers.ajio.com/"],
  ["Akamai", "https://www.akamai.com/careers/"],
  ["AlphaGrep", "https://www.alphagrep.com/careers"],
  ["Alphonso", "https://www.alphonso.tv/careers"],
  ["Amagi", "https://amagi.com/careers/"],
  ["Amazon", "https://www.amazon.jobs/"],
  ["American Express", "https://jobs.americanexpress.com/"],
  ["Angel One", "https://www.angelone.in/careers"],
  ["Ansys", "https://www.ansys.com/careers"],
  ["Anthem", "https://careers.antheminc.com/"],
  ["Apna", "https://apna.co/careers"],
  ["AppDynamics", "https://www.appdynamics.com/careers/"],
  ["Arcesium", "https://www.arcesium.com/careers"],
  ["Arista", "https://www.arista.com/en/company/careers"],
  ["Atlassian", "https://www.atlassian.com/company/careers"],
  ["AutoDesk", "https://www.autodesk.com/careers"],
  ["Auzmor", "https://www.auzmor.com/careers"],
  ["Avail Finance", "https://www.availfinance.in/careers"],
  ["Avalara", "https://www.avalara.com/us/en/careers.html"],
  ["BCG", "https://www.bcg.com/careers/default.aspx"],
  ["BNY Mellon", "https://www.bnymellon.com/us/en/careers/index.jsp"],
  ["Bain & Company", "https://www.bain.com/careers/"],
  ["Bankbazaar", "https://www.bankbazaar.com/careers.html"],
  ["Belzabar", "https://www.belzabar.com/careers"],
  ["Bharatpe", "https://www.bharatpe.com/careers"],
  ["Bigbasket", "https://www.bigbasket.com/careers/"],
  ["Biofourmis", "https://biofourmis.com/careers/"],
  ["Bizongo", "https://www.bizongo.com/careers"],
  ["Blackbuck", "https://www.blackbuck.com/careers"],
  ["Blinkit", "https://blinkit.tech/careers"],
  ["BloomReach", "https://www.bloomreach.com/careers"],
  ["Booking", "https://careers.booking.com/"],
  ["Bright Money", "https://www.brightmoney.co/careers"],
  ["Broadcom", "https://www.broadcom.com/company/careers"],
  ["Browserstack", "https://www.browserstack.com/careers"],
  ["Bukuwarung", "https://bukuwarung.com/careers"],
  ["Buyhatke", "https://www.buyhatke.com/careers"],
  ["Byjus", "https://byjus.com/careers/"],
  ["C2FO", "https://c2fo.com/careers/"],
  ["Cadence", "https://www.cadence.com/en_US/home/careers.html"],
  ["CashFree", "https://www.cashfree.com/careers"],
  ["Chargebee", "https://www.chargebee.com/careers"],
  ["Chegg", "https://www.chegg.com/jobs"],
  ["Chronus Software", "https://www.chronus.com/careers"],
  ["Cisco", "https://www.cisco.com/c/en/us/about/careers.html"],
  ["Citi Bank", "https://jobs.citi.com/"],
  ["Citrix", "https://www.citrix.com/about/careers/"],
  ["Citymall", "https://www.citymall.com/jobs"],
  ["Clarisights", "https://www.clarisights.com/careers"],
  ["ClearQuote", "https://www.clearquote.ai/careers"],
  ["ClearTax", "https://cleartax.in/s/careers"],
  ["Clear Trip", "https://www.cleartrip.com/corporate/careers"],
  ["Cloootrack", "https://www.clootrack.com/careers"],
  ["Cloud Lending", "https://www.cloudlendinginc.com/careers"],
  ["Clumio", "https://www.clumio.com/company/careers"],
  ["Credgenics", "https://www.credgenics.com/careers"],
  ["Codenation", "https://www.codingninjas.com/careers"],
  ["Cogoport", "https://www.cogoport.com/careers"],
  ["Cohesity", "https://www.cohesity.com/company/careers/"],
  ["Coinbase", "https://www.coinbase.com/careers"],
  ["Coinswitch", "https://coinswitch.co/careers"],
  ["CommercelQ", "https://www.commerceiq.ai/careers"],
  ["Commvault", "https://www.commvault.com/company/careers"],
  ["Confluent", "https://www.confluent.io/careers/"],
  ["CouchBase", "https://www.couchbase.com/careers"],
  ["Cred", "https://www.cred.club/careers"],
  ["Credit Suisse", "https://www.credit-suisse.com/about-us/en/careers.html"],
  ["Crowdfire", "https://www.crowdfireapp.com/careers"],
  ["Cult Fit", "https://www.cult.fit/careers"],
  ["DE Shaw", "https://www.deshawindia.com/careers.html"],
  ["Daily Rounds", "https://www.dailyrounds.org/careers"],
  ["Datadog", "https://www.datadoghq.com/careers/"],
  ["Dealshare", "https://www.dealshare.in/careers"],
  ["Delivery", "https://www.delivery.com/careers"],
  ["Dialpad", "https://www.dialpad.com/careers/"],
  ["Directi", "https://careers.directi.com/"],
  ["Dp world", "https://www.dpworld.com/careers"],
  ["Dream 11", "https://www.dream11.com/careers"],
  ["Dremio", "https://www.dremio.com/careers/"],
  ["Druva", "https://www.druva.com/careers/"],
  ["Duetshe bank", "https://www.db.com/careers/index_e.html"],
  ["Dunzo", "https://dunzo.com/careers"],
  ["Eightfold ai", "https://eightfold.ai/company/careers/"],
  ["Electronics Arts", "https://www.ea.com/careers"],
  ["Eltropy", "https://www.eltropy.com/careers"],
  ["Endurance", "https://www.endurance.com/careers"],
  ["Enfusion", "https://www.enfusion.com/careers"],
  ["Epifi", "https://www.epifi.com/careers"],
  ["Expedia", "https://lifeatexpedia.com/"],
  ["Falabella", "https://www.falabella.com.co/falabella-co/"],
  ["Fanclash", "https://www.fanclash.in/careers"],
  ["Far Eye", "https://www.fareye.com/careers"],
  ["FarEye", "https://www.fareye.com/careers"],
  ["Fedility Investments", "https://jobs.fidelity.com/"],
  ["Fleetx", "https://www.fleetx.io/careers"],
  ["Flipkart", "https://www.flipkartcareers.com/"],
  ["Flock", "https://www.flock.com/careers"],
  ["Today", "https://today.picnic.nl/jobs"],
  ["Fraazo", "https://fraazo.com/careers"],
  ["FreeCharge", "https://www.freecharge.in/"],
  ["FreshMenu", "https://careers.freshmenu.com/"],
  ["FreshWorks", "https://www.freshworks.com/company/careers/"],
  ["FrontRow", "https://www.frontrowed.com/careers"],
  ["FunPlus", "https://www.funplus.com/"],
  ["GE Health Care", "https://www.gehealthcare.com/about/careers"],
  ["Games 24x7", "https://www.games24x7.com/careers"],
  ["GamesKraft", "https://www.gameskraft.com/careers"],
  ["Gartner", "https://jobs.gartner.com/"],
  ["Glance", "https://www.glance.com/careers"],
  ["Gojek", "https://www.gojek.io/careers"],
  ["Goldman sachs", "https://www.goldmansachs.com/careers/"],
  ["GoodWorker", "https://www.goodworker.co/careers"],
  ["Google", "https://careers.google.com/"],
  ["Grab", "https://grab.careers/"],
  ["Graviton", "https://www.graviton.com/careers"],
  ["Groupon", "https://www.grouponcareers.com/"],
  ["Groww", "https://groww.in/careers"],
  ["Gupshup", "https://www.gupshup.io/careers"],
  ["Harness", "https://www.harness.io/company/careers/"],
  ["Headout", "https://www.headout.com/careers"],
  ["Hedge Fund", "https://www.hedgefundfundamentals.com/careers"],
  ["Hotstar", "https://careers.hotstar.com/"],
  ["Idrive", "https://www.idrive.com/aboutus/careers"],
  ["Indeed", "https://www.indeed.com/career"],
  ["IndiaMart", "https://www.indiamart.com/careers.html"],
  ["Infoblox", "https://www.infoblox.com/company/careers/"],
  ["InMobi", "https://www.inmobi.com/careers/"],
  ["Incred", "https://incred.com/careers/"],
  ["Incred finance", "https://incred.com/careers/"],
  ["Indegene", "https://www.indegene.com/careers"],
  ["Infra market", "https://www.inframarket.com/careers"],
  ["Inmobi", "https://www.inmobi.com/careers/"],
  ["Innovaccer", "https://innovaccer.com/careers/"],
  ["Instamojo", "https://www.instamojo.com/careers"],
  [
    "Intel",
    "https://www.intel.com/content/www/us/en/jobs/locations/india/jobs.html",
  ],
  ["Intuit", "https://www.intuit.com/careers/"],
  ["Irvine", "https://www.irvine.com/careers"],
  ["Juspay", "https://juspay.in/careers"],
  ["KLA", "https://www.kla.com/company/careers/"],
  ["Kredit Bee", "https://www.kreditbee.in/careers"],
  ["Licious", "https://www.licious.in/careers"],
  ["Livspace", "https://www.livspace.com/careers"],
  ["Locus", "https://locus.sh/careers"],
  ["MakeMyTrip", "https://www.makemytrip.com/careers"],
  ["Mentor Graphics", "https://www.mentor.com/careers"],
  ["Meesho", "https://meesho.com/careers"],
  ["Microsoft", "https://careers.microsoft.com/"],
  ["MindTickle", "https://www.mindtickle.com/careers"],
  ["MoonFrog", "https://www.moonfroglabs.com/careers"],
  ["MotorQ", "https://www.motorq.co/careers"],
  ["MyKaarma", "https://www.mykaarma.com/careers"],
  ["Myntra", "https://www.myntra.com/careers"],
  ["Nas Academy", "https://nasacademy.com/careers"],
  ["Navi", "https://www.navi.com/careers"],
  ["Nektar ai", "https://www.nektar.ai/careers"],
  ["NetApp", "https://www.netapp.com/us/careers/"],
  ["Ninjacart", "https://www.ninjacart.in/careers"],
  ["NoBroker", "https://www.nobroker.in/careers"],
  ["Noccarc", "https://www.noccarc.com/careers"],
  ["Nurture Farm", "https://www.nurture.farm/careers"],
  ["Nutanix", "https://www.nutanix.com/company/careers"],
  ["Nvidia", "https://www.nvidia.com/en-us/about-nvidia/careers/"],
  ["OCI", "https://www.oci.com/careers"],
  ["OLX Group", "https://www.olxgroup.com/careers"],
  ["OkCredit", "https://www.okcredit.in/careers"],
  ["Ola", "https://careers.olacabs.com/"],
  ["Oppo", "https://www.oppo.com/in/about-us/careers/"],
  ["Oracle", "https://www.oracle.com/corporate/careers/"],
  ["Oyorooms", "https://www.oyorooms.com/careers"],
  ["PayPal", "https://www.paypal.com/us/webapps/mpp/jobs"],
  ["PayTM", "https://paytm.com/about-us/careers/"],
  ["PhonePe", "https://www.phonepe.com/en/careers"],
  ["Plum", "https://www.plumhq.com/careers"],
  ["PokerDangal", "https://www.pokerdangal.com/careers"],
  ["Postman", "https://www.postman.com/company/careers/"],
  ["Practo", "https://www.practo.com/company/careers"],
  ["Pristyn Care", "https://www.pristyncare.com/careers"],
  ["PumaPay", "https://www.pumapay.io/careers"],
  ["Purplle", "https://www.purplle.com/careers"],
  ["Qualcomm", "https://www.qualcomm.com/company/careers"],
  ["QuantBox", "https://www.quantbox.com/careers"],
  ["Quikr", "https://www.quikr.com/jobs"],
  ["Razorpay", "https://razorpay.com/careers/"],
  ["Recko", "https://www.recko.com/careers"],
  ["Redbus", "https://www.redbus.in/careers"],
  ["Reddit", "https://www.redditinc.com/careers"],
  ["Reface", "https://www.reface.app/careers"],
  ["Reforge", "https://www.reforge.com/careers"],
  ["Rekindle", "https://www.rekindle.co.in/careers"],
  ["Rivigo", "https://www.rivigo.com/careers"],
  ["Roblox", "https://corp.roblox.com/careers/"],
  ["Rubrik", "https://www.rubrik.com/company/careers"],
  ["Rupeek", "https://www.rupeek.com/careers"],
  ["SAP", "https://www.sap.com/careers.html"],
  ["Sasta Sundar", "https://www.sastasundar.com/career"],
  ["ShareChat", "https://we.sharechat.com/careers"],
  ["Shell", "https://www.shell.in/careers.html"],
  ["ShopX", "https://shopx.in/careers"],
  ["Shuttl", "https://www.shuttl.com/careers"],
  ["Siemens", "https://new.siemens.com/global/en/company/jobs.html"],
  ["Sigmoid", "https://www.sigmoid.com/careers"],
  ["SigTuple", "https://www.sigtuple.com/careers"],
  ["Silverlake", "https://www.silverlake.com/"],
  ["Simility", "https://www.simility.com/careers"],
  ["Simpl", "https://www.simpl.com/careers"],
  ["SimpliLend", "https://www.simplilend.com/careers"],
  ["SimpliLearn", "https://www.simplilearn.com/careers"],
  ["Simpli Work", "https://simpliwork.com/careers"],
  ["Slack", "https://slack.com/careers"],
  ["Snapdeal", "https://www.snapdeal.com/info/careers"],
  ["Sokrati", "https://www.sokrati.com/careers"],
  ["Sonrai Security", "https://sonraisecurity.com/careers/"],
  ["Sophos", "https://www.sophos.com/en-us/about-us/careers.aspx"],
  ["Soundcloud", "https://soundcloud.com/careers"],
  ["Sprinklr", "https://www.sprinklr.com/careers/"],
  ["Square Yards", "https://www.squareyards.com/careers"],
  ["Squarespace", "https://www.squarespace.com/careers"],
  ["StackRoute", "https://www.stackroute.in/careers"],
  ["Starfield", "https://starfield.tech/"],
  ["Stellar", "https://www.stellarinfo.com/careers.htm"],
  ["Sumo Logic", "https://www.sumologic.com/company/careers/"],
  ["Swiggy", "https://www.swiggy.com/careers"],
  ["Symantec", "https://www.symantec.com/careers"],
  ["TCS", "https://www.tcs.com/careers"],
  ["Talview", "https://www.talview.com/careers"],
  ["Target", "https://jobs.target.com/"],
  ["Tata Motors", "https://www.tatamotors.com/careers/"],
  ["Tekion", "https://www.tekion.com/careers"],
  ["Telus", "https://www.telusinternational.com/careers"],
  ["TheMathCompany", "https://themathcompany.com/careers"],
  ["ThoughtSpot", "https://www.thoughtspot.com/careers"],
  ["Tiaa Global", "https://www.tiaa.org/public/about-tiaa/careers"],
  ["Tiger Analytics", "https://www.tigeranalytics.com/careers"],
  ["Tinder", "https://www.gotinder.com/jobs"],
  ["ToneTag", "https://tonetag.com/careers"],
  ["Toppr", "https://www.toppr.com/careers"],
  ["Toyota", "https://www.toyota.com/usa/careers/"],
  ["TraceLink", "https://www.tracelink.com/careers"],
  ["Tradeteq", "https://www.tradeteq.com/careers"],
  ["TransUnion", "https://www.transunion.com/careers"],
  ["Traveloka", "https://www.traveloka.com/careers"],
  ["TrueCaller", "https://www.truecaller.com/careers"],
  ["TrueLayer", "https://www.truelayer.com/careers"],
  ["TrueCaller", "https://www.truecaller.com/careers"],
  ["Twitter", "https://careers.twitter.com/"],
  ["Uber", "https://www.uber.com/global/en/careers/"],
  ["Unacademy", "https://unacademy.com/careers"],
  ["Unbxd", "https://unbxd.com/careers"],
  ["Unilever", "https://www.unilever.com/careers/"],
  ["UnitedHealth Group", "https://careers.unitedhealthgroup.com/"],
  ["UpGrad", "https://www.upgrad.com/careers"],
  ["Urban Company", "https://www.urbancompany.com/careers"],
  ["Valocity", "https://www.valocity.co.nz/careers"],
  ["Vedantu", "https://www.vedantu.com/careers"],
  ["Verizon", "https://www.verizon.com/about/careers"],
  ["VerSe Innovation", "https://www.verve.com/careers"],
  ["Vimeo", "https://vimeo.com/jobs"],
  ["Visa", "https://www.visa.co.in/careers.html"],
  ["Vymo", "https://www.getvymo.com/careers"],
  ["Walmart Labs", "https://careers.walmart.com/"],
  ["Walmart", "https://careers.walmart.com/"],
  ["Walmart Global Tech", "https://careers.walmart.com/"],
  ["Wattmonk", "https://www.wattmonk.com/careers"],
  ["Wibmo", "https://www.wibmo.com/careers"],
  ["Wingify", "https://wingify.com/careers"],
  ["Wipro", "https://careers.wipro.com/"],
  ["Wizrocket", "https://www.clevertap.com/careers"],
  ["Xoriant", "https://www.xoriant.com/careers"],
  ["Yatra", "https://www.yatra.com/careers"],
  ["Yelp", "https://www.yelp.com/careers"],
  ["Yes Bank", "https://www.yesbank.in/careers"],
  ["Zebpay", "https://zebpay.com/careers"],
  ["Zemoso Labs", "https://www.zemosolabs.com/careers"],
  ["Zenoti", "https://www.zenoti.com/careers"],
  ["Zeta", "https://www.zeta.tech/careers"],
  ["Zilingo", "https://www.zilingo.com/careers"],
  ["Zoom", "https://zoom.us/careers"],
  ["Zycus", "https://www.zycus.com/careers"],
  ["Zynga", "https://www.zynga.com/careers"],
  ["Indiagold", "https://indiagold.com/careers/"],
  ["Indmoney", "https://www.indmoney.com/careers"],
  ["InsideView", "https://www.insideview.com/company/careers/"],
  ["Ion Trading", "https://www.iongroup.com/careers/"],
  ["Itilite", "https://www.itilite.com/careers"],
  ["Ixigo", "https://www.ixigo.com/careers"],
  ["Jio", "https://careers.jio.com/"],
  ["JPMC", "https://careers.jpmorgan.com/"],
  ["Jumio", "https://www.jumio.com/company/careers/"],
  ["Jungle Games", "https://www.junglegames.in/careers"],
  ["Juniper Networks", "https://www.juniper.net/us/en/company/careers/"],
  ["Jupiter Money", "https://jupiter.money/careers"],
  ["Khatabook", "https://khatabook.com/careers"],
  ["Komprise", "https://www.komprise.com/careers/"],
  ["Kuvera", "https://kuvera.in/careers"],
  ["LambdaTest", "https://www.lambdatest.com/careers/"],
  ["Leap Finance", "https://www.leapfinance.com/careers/"],
  ["Leena ai", "https://leena.ai/careers"],
  ["Lenskart", "https://www.lenskart.com/careers"],
  ["Limeroad", "https://www.limeroad.com/careers"],
  ["Linkedin", "https://www.linkedin.com/company/linkedin/careers"],
  ["Ling", "https://www.lingvanex.com/careers"],
  ["Loco", "https://loco.live/careers"],
  ["MPL", "https://www.mpl.live/careers"],
  ["Magnitude", "https://www.magnitude.com/company/careers/"],
  ["Mastercard", "https://www.mastercard.us/en-us/about-mastercard/careers/"],
  ["MathWorks", "https://www.mathworks.com/company/jobs.html"],
  ["McKinsey", "https://www.mckinsey.com/careers"],
  ["Medianet", "https://www.medianet.com/careers/"],
  ["Meidatek", "https://www.mediatek.com/careers"],
  ["Mfine", "https://www.mfine.co/careers/"],
  ["MoenGage", "https://www.moengage.com/careers/"],
  ["Money Control", "https://www.moneycontrol.com/careers/"],
  ["Moneyview", "https://www.moneyview.in/careers/"],
  ["Morgan Stanley", "https://www.morganstanley.com/careers"],
  ["MSC", "https://www.msc.com/careers"],
  ["NK Securities", "https://www.nksecurities.com/careers"],
  ["National Instruments", "https://www.ni.com/en-in/about-ni/careers.html"],
  ["Netomi", "https://www.netomi.com/company/careers/"],
  ["NewFold Digital", "https://newfolddigital.com/careers"],
  ["Nference", "https://www.nference.ai/careers/"],
  ["Nike", "https://jobs.nike.com/"],
  ["Oyo", "https://www.oyorooms.com/careers/"],
  ["Palo Alto", "https://www.paloaltonetworks.com/company/careers"],
  ["PayU", "https://www.payu.com/careers"],
  ["Paypal", "https://www.paypal.com/us/webapps/mpp/jobs"],
  ["Paytm", "https://paytm.com/careers"],
  ["Peak Ai", "https://peak.ai/careers/"],
  ["PharmEasy", "https://pharmeasy.in/careers/"],
  ["Philips", "https://www.philips.co.in/careers"],
  ["Phonepe", "https://www.phonepe.com/careers/"],
  ["Pickrr", "https://pickrr.com/careers"],
  ["Plivo", "https://www.plivo.com/careers/"],
  ["PlumHQ", "https://www.plumhq.com/careers"],
  ["Porter", "https://www.porter.in/careers"],
  ["Progress", "https://www.progress.com/company/careers"],
  ["Property Guru", "https://www.propertyguru.com.sg/careers"],
  ["Prophecy io", "https://www.prophecy.io/careers/"],
  ["Public Sapient", "https://www.publicis.sapient.com/careers"],
  ["Quad Eye", "https://quad-eye.com/careers/"],
  ["Quizizz", "https://www.quizizz.com/jobs"],
  ["Rain Instant Pay", "https://rain.financial/careers/"],
  ["Rebel Foods", "https://www.rebelfoods.com/careers"],
  ["Reliance Retail", "https://relianceretail.com/careers"],
  ["Revolut", "https://jobs.lever.co/revolut"],
  ["Rippling", "https://www.rippling.com/careers"],
  ["SABRE", "https://www.sabre.com/careers/"],
  ["SAP Labs", "https://www.sap.com/india/about/careers.html"],
  ["Salesforce", "https://www.salesforce.com/company/careers/"],
  ["Salesken", "https://salesken.ai/careers/"],
  ["Samsung", "https://www.samsung.com/in/aboutsamsung/careers/"],
  ["Sapient", "https://www.sapientrazorfish.com/careers"],
  ["Schlumberger", "https://www.slb.com/careers"],
  ["SenseHq", "https://www.sensehq.co/careers"],
  ["Servicenow", "https://www.servicenow.com/company/careers.html"],
  ["Shiprocket", "https://www.shiprocket.in/careers/"],
  ["Sigtuple", "https://www.sigtuple.com/careers/"],
  ["Sixt", "https://www.sixt.jobs/"],
  ["Smart Coin Financials", "https://www.smartcoin.co.in/careers/"],
  ["Snowflake", "https://www.snowflake.com/careers/"],
  ["SocGen", "https://careers.societegenerale.com/"],
  ["Sostronk", "https://www.sostronk.com/careers"],
  ["Spinny", "https://www.spinny.com/careers"],
  ["SplashLearn", "https://www.splashlearn.com/careers/"],
  ["Stashfin", "https://www.stashfin.com/careers/"],
  ["Stripe", "https://stripe.com/jobs"],
  ["Sumologic", "https://www.sumologic.com/company/careers/"],
  ["Synopsys", "https://www.synopsys.com/company/careers.html"],
  ["Tata 1mg", "https://www.1mg.com/careers"],
  ["Telstra", "https://careers.telstra.com/"],
  ["Tesco", "https://www.tesco-careers.com/"],
  ["Tesla", "https://www.tesla.com/careers"],
  ["Texas Instruments", "https://careers.ti.com/"],
  ["Times Internet", "https://www.timesinternet.in/careers/"],
  ["Tokopedia", "https://www.tokopedia.com/careers/"],
  ["TomTom", "https://www.tomtom.com/careers/"],
  ["Tower Research Capital", "https://www.tower-research.com/careers/"],
  ["Trifacta", "https://www.trifacta.com/company/careers/"],
  ["Trink", "https://www.trinknow.com/careers"],
  ["TruEra", "https://www.truera.com/careers/"],
  ["Turvo", "https://www.turvo.com/careers/"],
  ["Twillio", "https://www.twilio.com/company/careers"],
  ["UOLO", "https://www.uolo.in/careers"],
  ["Udaan", "https://www.udaan.com/careers"],
  ["UiPath", "https://www.uipath.com/company/careers"],
  ["Upstox", "https://www.upstox.com/careers/"],
  ["Urban Ladder", "https://www.urbanladder.com/careers"],
  ["Vmware", "https://careers.vmware.com/"],
  ["Vogo", "https://www.vogo.in/careers/"],
  ["Wells Fargo", "https://www.wellsfargo.com/about/careers/"],
  ["Western Digital", "https://www.westerndigital.com/company/careers"],
  ["Whatfix", "https://whatfix.com/careers/"],
  ["Winzo", "https://winzogames.com/careers"],
  ["Wooger", "https://www.woogerworks.com/careers/"],
  ["World Quant", "https://www.worldquant.com/careers"],
  ["Xerox Research", "https://www.xerox.com/en-us/jobs/research-innovation"],
  ["Xilinx", "https://careers.xilinx.com/"],
  ["Yellow AI", "https://www.yellow.ai/careers/"],
  ["Yubi", "https://www.yubi.ai/careers/"],
  ["Zendrive", "https://www.zendrive.com/careers/"],
  ["Zenefits", "https://www.zenefits.com/careers/"],
  ["Zerodha", "https://zerodha.com/careers"],
  ["Zomato", "https://www.zomato.com/careers"],
]);

async function getRandomCompany() {
  const randomIndex = Math.floor(Math.random() * companies.length);
  const Name = companies[randomIndex],
    Url = companyCareerLinks.get(Name);
  return { name: Name, carrer_url: Url };
}

module.exports = {
  getRandomCompany: getRandomCompany,
};
